### ISSUE TITLE
[Feature Request] - Help porting Linux Homebrew to ARM and tuning for AWS Linux 2022

### ISSUE THREAD

**Issue by chadbrewbaker** [amazonlinux/amazon-linux-2022#103]
**Is your feature request related to a problem? Please describe.**
I would prefer to keep aws-linux-2022 slim and rely on Homebrew for bleeding edge binaries.

**Describe the solution you'd like**
Help fixing support for ARM installer for Linux Homebrew and ensure packages compile well for AWS Linux 2022.

As a side-goal I would like the LLVM toolchain built alongside Rust nightly so you can build with binary compatible Clang.

**Describe alternatives you've considered**
[spac](https://github.com/spack/spack)  

**Additional context**
This will also be an amazing test suite to tease out bugs in AWS Linux 2022.

- [ ]  Fix ARM installer
- [ ]  Seed major packages for ARM
- [ ]  Come up with alternate S3 storage so AWS Linux 2022 containers can lazy load binaries as they need.
- [ ]  Tune major packages to AWS Linux 2022 
- [ ]  Set up a full build of Linux Homebrew as a test suite for AWS Linux 2022

**Comment by stewartsmith** [comment]
I'm trying to understand the specifics of the ask here: is it for AWS to port the Homebrew package manager over to AL2022?

**Comment by chadbrewbaker** [comment]
It is to get the homebrew packages building under AWSLinux2022 for ARM. The exercise will uncover a lot of distro bugs.

**Comment by stewartsmith** [comment]
Where porting or optimization is required, we prefer to work directly in the upstream projects, and cherry picking any fixes needed into the packages we ship as part of the OS. We do not currently have plans to work on alternate packaging systems such as Homebrew, instead focusing on Amazon Linux itself, and bringing things into the distribution as-needed.
