### ISSUE TITLE
[Bug] - Disabled cloud-init 'init-local' stage in EC2 instance breaks "First Boot Determination" check

### ISSUE THREAD

**Issue by jeremiahsnapp** [amazonlinux/amazon-linux-2022#104]
**Describe the bug**

The recent release of the amazon linux 2022 x86_64 AMI, `al2022-ami-2022.0.20220308.1-kernel-5.15-x86_64` `ami-0f7be56106b370c1f`, adds a systemd override file `/usr/lib/systemd/system/cloud-init-local.service.d/skip-ec2.conf` with the following contents.

```
# Skip cloud-init-local if we're running in Amazon EC2
[Unit]
ConditionVirtualization=!amazon
```

This disables cloud-init's `init-local` stage in EC2 instances. The `init-local` stage is required for the [First Boot Determination check](https://cloudinit.readthedocs.io/en/latest/topics/boot.html#first-boot-determination) which ensures that a new instance will run cloud-init's "first boot" related processes such as rotating SSH server keys and populating `~/.ssh/authorized_keys` so a user can log into the instance.

When `init-local` is skipped a user is prevented from using an AMI that was built from an instance's EBS volume. The instance built from that AMI will skip many cloud-init processes because it looks like the instance has already booted once. This prevents even the most basic things such as populating `~/.ssh/authorized_keys` so a user can log into the instance.

**To Reproduce**

I used packer to create my AMIs but here are the general steps to reproduce the behavior:

1. Create an EC2 instance using `ami-0f7be56106b370c1f` AMI
1. Optionally set a password for the ec2-user so you can login using the serial console when ssh keys don't work
1. Make an AMI from the instance
1. Create a new EC2 instance using the new AMI
1. Try to login to the instance using ssh keys. Login will fail.

**Expected behavior**

When an AMI is created from an EC2 instance and used in a new EC2 instance it should boot and cloud-init should recognize the first boot of the instance and run cloud-init procedures accordingly.

**Workarounds**

The first workaround is to delete `/usr/lib/systemd/system/cloud-init-local.service.d/skip-ec2.conf` before making the AMI. That way cloud-init's `init-local` stage runs in new instances made from the AMI.

The other workaround is to run `cloud-init clean --logs` before making the AMI. This deletes cloud-init data related to the instance so when a new instance is made using the AMI cloud-init won't see any preexisting data and therefore recognize it is a first boot and run appropriate cloud-init procedures. Perhaps this is what I should have been doing all along so I'll probably use this workaround. However, I maintain more than 30 different platforms in AWS that use cloud-init and this is the first time I had this problem.

**Comment by nmeyerhans** [comment]
> The other workaround is to run cloud-init clean --logs before making the AMI. This deletes cloud-init data related to the instance so when a new instance is made using the AMI cloud-init won't see any preexisting data and therefore recognize it is a first boot and run appropriate cloud-init procedures. Perhaps this is what I should have been doing all along so I'll probably use this workaround. However, I maintain more than 30 different platforms in AWS that use cloud-init and this is the first time I had this problem.

Yes, you should be doing this anyway, as cloud-init's cached state can potentially contain sensitive data.

In any case, a fix for this issue has been committed and will be reflected in the next publication of AL2022 AMIs.
