### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by LiteWait** [amazonlinux/amazon-linux-2022#108]
Not holding AWSs feet to the fire, but I am making a huge commitment to upgrade our instances from AWS Linux 1.  I really don't want to migrate to AWS Linux 2, only to have to do it all over again with AL2022.

I'll wait ... are we talking months till release or ...end of year?

Again won't hold you to it, but I need to plan.

**Comment by liesenml** [comment]
Hello- our target release for AL2022 external is in Q3 2022. There is also a tech preview for al2022 available currently. Let me know if that helps!
