### ISSUE TITLE
[Bug] - Missing dependency perl-DBD-MariaDB for mariadb105-server-utils

### ISSUE THREAD

**Issue by RichardDale** [amazonlinux/amazon-linux-2022#110]
**Describe the bug**
mariadb105-server-utils cannot be installed because it perl-DBD-MariaDB is not in the repo.  perl-DBD-MySQL is, however, in the repo and should either use that, or perl-DBD-MariaDB should be in the repo.

**To Reproduce**
dnf install mariadb105-server-utils

**Expected behavior**
perl-DBD-MariaDB as a dependency is installed (or perl-DBD-MySQL is used as a susbittue)

**OS version**
 - AL2022 20220419

**Workaround**
A hacky workaround is to download the perl-DBD-MariaDB rpm from a different source

``wget https://www.rpmfind.net/linux/fedora/linux/releases/34/Everything/x86_64/os/Packages/p/perl-DBD-MariaDB-1.21-11.fc34.x86_64.rpm``
``rpm -i perl-DBD-MariaDB-1.21-11.fc34.x86_64.rpm``

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by stewartsmith** [comment]
The `2022.0.20220728` release contains `perl-DBD-MariaDB`
