### ISSUE TITLE
[Feature Request] - Network interface naming scheme (eth0 vs ens5)

### ISSUE THREAD

**Issue by talawahtech** [amazonlinux/amazon-linux-2022#111]
The Amazon Linux 2 and Fedora 34 AMIs currently use the `net.ifnames=0` boot parameter to preserve the traditional interface naming scheme (eth0, eth1) whereas the AL 2022 AMI doesn't use that parameter so interfaces are automatically renamed to the newer scheme (ens5, ens6).

Is the plan for the GA version of AL 2022 to stick with the new scheme or go back to the traditional scheme?

**Comment by nmeyerhans** [comment]
AL2022 will use systemd's slot based interface naming scheme.

**Comment by talawahtech** [comment]
Ok cool. Might be something to to include if you guys put together a doc listing the differences between AL2 and AL2022. I am sure there are lots of scripts out there that hardcode `eth0`.
