### ISSUE TITLE
Is there any image for VMware?

### ISSUE THREAD

**Issue by vovantamvn** [amazonlinux/amazon-linux-2022#112]
### Discussed in https://github.com/amazonlinux/amazon-linux-2022/discussions/106

<div type='discussions-op-text'>

<sup>Originally posted by **vovantamvn** April  5, 2022</sup>
I need to test this image, but I can't find it. Is it available now?</div>

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.
