### ISSUE TITLE
[Package Request] - yaml-cpp

### ISSUE THREAD

**Issue by talawahtech** [amazonlinux/amazon-linux-2022#118]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
> yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.

https://github.com/jbeder/yaml-cpp

**Is this an update to existing package or new package request?**
New package.

**Is this package available in Amazon Linux 2?**
Yes, yaml-cpp and yaml-cpp-devel are available via EPEL. They are also available in Fedora 34.

**Number of users impacted**
yaml-cpp-devel is a dependency of the Seastar server framework http://seastar.io/.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by stewartsmith** [comment]
The `2022.0.20220728` release has the `yaml-cpp` package
