### ISSUE TITLE
[Package Request] - Container-selinux

### ISSUE THREAD

**Issue by aceclan** [amazonlinux/amazon-linux-2022#125]
Container-selinux is a new package, which could be useful when using docker with selinux enabled. 

This should be a base package that will save the time of creating policies for selinux.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests and will reply to this ticket by with our evaluation.

**Comment by edwardvdv** [comment]
Duplicate of https://github.com/amazonlinux/amazon-linux-2022/issues/56

**Comment by stewartsmith** [comment]
Closing as duplicate of https://github.com/amazonlinux/amazon-linux-2022/issues/56
