### ISSUE TITLE
[Package Request] - amazon-ssm-agent

### ISSUE THREAD

**Issue by stewartsmith** [amazonlinux/amazon-linux-2022#13]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
`amazon-ssm-agent` - the SSM Agent packaged for Amazon Linux.

**Is this an update to existing package or new package request?**
New package for AL2022.

**Is this package available in Amazon Linux 2?**
Yes.

**Comment by pcolazurdo** [comment]
+1

**Comment by ramnamy** [comment]
+1

**Comment by crabby345** [comment]
Essential to be an out of the box solution. Having to install via userdata at the moment to even reach the instance.

**Comment by stewartsmith** [comment]
While not in our 2022.0.20220628 release (we hit a minor technical issue during release), it's coming in the next one.

**Comment by stewartsmith** [comment]
The `amazon-ssm-agent` is available in the `2022.0.20220728` release (possibly an earlier one too, but it's certainly in that release)

**Comment by beanaroo** [comment]
Great news!

Fresh launch of `2022.0.20220728` shows the unit is disabled on boot. Is this expected?

```
[root@ip-10-37-254-164 ~]# systemctl status amazon-ssm-agent
○ amazon-ssm-agent.service - amazon-ssm-agent
     Loaded: loaded (/usr/lib/systemd/system/amazon-ssm-agent.service; disabled; vendor preset: disabled)
     Active: inactive (dead)
```

**Comment by brandondwhite** [comment]
> Great news!
> 
> Fresh launch of `2022.0.20220728` shows the unit is disabled on boot. Is this expected?
> 
> ```
> [root@ip-000-000-000-000 ~]# systemctl status amazon-ssm-agent
> ○ amazon-ssm-agent.service - amazon-ssm-agent
>      Loaded: loaded (/usr/lib/systemd/system/amazon-ssm-agent.service; disabled; vendor preset: disabled)
>      Active: inactive (dead)
> ```

Seeing the same issue, this was not disabled on AL2 AMIs.
