### ISSUE TITLE
[Package Request] - amazon-cloudwatch-agent

### ISSUE THREAD

**Issue by Jpk518** [amazonlinux/amazon-linux-2022#132]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
`amazon-cloudwatch-agent` - unified cloudwatch agent for collecting system metrics

**Is this an update to existing package or new package request?**
New package for AL2022

**Is this package available in Amazon Linux 2?**
 Yes

**Comment by stewartsmith** [comment]
The `amazon-cloudwatch-agent` package is part of the `2022.0.20220728` release.
