### ISSUE TITLE
[Bug] "rubygem-puma" package has disappeared in 6/28

### ISSUE THREAD

**Issue by vladimir-ryazanov** [amazonlinux/amazon-linux-2022#141]
**Describe the bug**
"rubygem-puma" has silently disappeared from the repository starting from `public.ecr.aws/amazonlinux/amazonlinux:2022.0.20220628.8`

**To Reproduce**
```
# dnf install rubygem-puma
No match for argument: rubygem-puma
Error: Unable to find a match: rubygem-puma
```

**Expected behavior**
The package installs (works on `2022.0.20220531.0`)

**Desktop (please complete the following information):**
Docker Desktop 4.9.1 (81317) / Docker Engine Engine: 20.10.16 on macOS Big Sur. AL base image tag as mentioned above.

**Additional context**
The removal of the package is not documented in the [release notes](https://docs.aws.amazon.com/linux/al2022/release-notes/relnotes-20220628.html), so it is not clear whether we should wait for its reappearance in the next release or switch to a DIY installation.

**Comment by stewartsmith** [comment]
We haven't been doing a full diff of what's been added/removed in each preview milestone, as that can get fairly noisy, and have instead indexed on keeping the list of what's changed from AL2 up to date.

Without looking internally, I do not believe that package is coming back, and so you should look at bringing it in yourself.

We have been keeping the set of gems (and modules for other languages) to a minimum of what we need for the OS, instead delegating to the idiomatic packaging systems for other modules.

**Comment by vladimir-ryazanov** [comment]
Thank you, that clarifies it.
