### ISSUE TITLE
[Package Request] - amazon-ecr-credential-helper

### ISSUE THREAD

**Issue by rerooted** [amazonlinux/amazon-linux-2022#153]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

amazon-ecr-credential-helper

https://github.com/awslabs/amazon-ecr-credential-helper

**Is this an update to existing package or new package request?**

New

**Is this package available in Amazon Linux 2?**

Yes, available via amazon-linux-extras

**Number of users impacted**

Unknown

This is useful to avoid having to store long lasting login credentials on the instance (eg aws ecs get-login-password -> docker login).

**Comment by stewartsmith** [comment]
This is now available in AL2022:

```
bash-5.1# dnf info amazon-ecr-credential-helper
Last metadata expiration check: 3:50:32 ago on Fri Nov  4 16:47:43 2022.
Available Packages
Name         : amazon-ecr-credential-helper
Version      : 0.6.0
Release      : 1.amzn2022
Architecture : x86_64
Size         : 2.2 M
Source       : amazon-ecr-credential-helper-0.6.0-1.amzn2022.src.rpm
Repository   : amazonlinux
Summary      : Amazon ECR Docker Credential Helper
License      : Apache 2.0
Description  : The Amazon ECR Docker Credential Helper is a credential helper
             : for the Docker daemon that makes it easier to use Amazon Elastic
             : Container Registry.

```
