### ISSUE TITLE
[Package Request] - unzip

### ISSUE THREAD

**Issue by Vloeck** [amazonlinux/amazon-linux-2022#161]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
`unzip` A utility for unpacking zip files

**Is this an update to existing package or new package request?**
New package request

**Is this package available in Amazon Linux 2?**
Package is automatically installed in AL2

**Number of users impacted**
probably several

**Comment by stewartsmith** [comment]
`unzip` is available in the package repositories and can be installed with `dnf install -y unzip`.

The list of packages in base AMIs and container images can shrink over time, and we try to include both sensible defaults in AMIs, as well as the minimal needed.

We are not looking at making the base images larger by adding packages though.
