### ISSUE TITLE
[Package Request] - nano

### ISSUE THREAD

**Issue by Vloeck** [amazonlinux/amazon-linux-2022#162]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
`nano` A small text editor

**Is this an update to existing package or new package request?**
new package request

**Is this package available in Amazon Linux 2?**
Package is automatically installed in AL2

**Number of users impacted**
probably several

**Comment by stewartsmith** [comment]
The `nano` package can be installed with `dnf install -y nano` - the set of packages we are keeping on AMIs and container images is minimal, in order to reduce the disk space and patching requirements for customers.
