### ISSUE TITLE
[Package Request] - bash-completion

### ISSUE THREAD

**Issue by Vloeck** [amazonlinux/amazon-linux-2022#163]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
`bash-completion` Programmable completion for Bash

**Is this an update to existing package or new package request?**
new package request

**Is this package available in Amazon Linux 2?**
Package is automatically installed in AL2

**Number of users impacted**
probably several

**Comment by stewartsmith** [comment]
We are keeping the base set of packages in the AMIs and container images to a minimum, and `bash-completion` can easily be installed with `dnf install -y bash-completion`.
