### ISSUE TITLE
[Bug] - Maven HTTP code seems to be broken

### ISSUE THREAD

**Issue by arnsholt** [amazonlinux/amazon-linux-2022#175]
**Describe the bug**
The part of Apache Maven downloading over HTTP packaged in AL2022 seems to be missing and/or broken.

**To Reproduce**
1. Install maven: `dnf install maven`
2. Run the plugin to generate a blank project: `mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false`
4. See very deep stack trace:

```
[INFO] Scanning for projects...
[WARNING] Error injecting: org.apache.maven.wagon.providers.http.HttpWagon$__sisu20
java.lang.TypeNotPresentException: Type org.apache.maven.wagon.providers.http.HttpWagon$__sisu20 not present
```

**Expected behavior**
A generated Maven template project.

**Additional context**
I've tried to install various other Maven packages (notably the maven-wagon-* packages), but have been unable to find the ones with the missing classes if they exist.

Tested on releasever 2022.0.20220824.

**Comment by keithaws** [comment]
This has been resolved in the latest release candidate. I've verified that the command runs as expected, without error, and creates a directory named my-app with a pom.xml and src directory.
