### ISSUE TITLE
[Bug] - America/Santiago DST change has been postponed 1 week, but it didn't in AL2

### ISSUE THREAD

**Issue by sercasti** [amazonlinux/amazon-linux-2022#185]
**Describe the bug**
The chilean government [postponed](https://techcommunity.microsoft.com/t5/daylight-saving-time-time-zone/interim-guidance-on-2022-time-zone-updates-for-chile/ba-p/3598290#:~:text=On%20August%208%2C%202022%2C%20the,time%20will%20advance%2060%20minutes.) the DST change from Sept 3rd to Sept 9th, this is not reflected on EC2 instances running Amazon Linux 2

**To Reproduce**
1. Start and EC2 instance using AL2
2. Set the timezone to America/Santiago
3. Notice the DST changed on 2022-09-03 using the "timedatectl" command
4. See error (DST changed when it shouldn't have)

**Expected behavior**
DST change should be applied on Sept 9th

**Screenshots**

**Desktop (please complete the following information):**
 - OS: AL2
 - Version 5.10.130-118.517.amzn2.x86_64

**Additional context**
This is affecting all customers using AL2 with "America/Santiago" configured as timezone

**Comment by stewartsmith** [comment]
There should be a tzdata package update available via 'yum update tzdata' that'd bring in the update. Since it's not a Critical or Important security update, it's not pulled in on launch on AL2, and hasn't yet made it into AMIs.

AL2022 didn't get the update yet though.

**Comment by sercasti** [comment]
yup, yum update tzdata fixed it since version 2022b, thanks!
