### ISSUE TITLE
[Package Request] - amazon-linux-extras

### ISSUE THREAD

**Issue by osama004** [amazonlinux/amazon-linux-2022#188]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
amazon-linux-extras
**Is this an update to existing package or new package request?**

**Is this package available in Amazon Linux 2?**

**Number of users impacted**

**Comment by stewartsmith** [comment]
Amazon Linux 2 has `amazon-linux-extras`, while AL2022 does not.

If there are specific versions of specific packages which you're looking for, we can look at adding them to Amazon Linux 2022.

**Comment by daniejstriata** [comment]
> Amazon Linux 2 has `amazon-linux-extras`, while AL2022 does not.
> 
> If there are specific versions of specific packages which you're looking for, we can look at adding them to Amazon Linux 2022.

Can I install EPEL 9 on AL2002?
