### ISSUE TITLE
[Package Request] - how to install extras packages in amazonlinux:2022 docker image

### ISSUE THREAD

**Issue by citycan1991** [amazonlinux/amazon-linux-2022#189]
Hi, I'm try to use amazonlinux:2022  as our base docker image, and I can see [amazon-linux-extras] this command everywhere.
but actually I got command not found after input amazon-linux-extras install xxx.

By the way, the default yum repo provide few packages. when I tried to add epel repo(by command:
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm), I got this error:
Error:
Problem: conflicting requests

nothing provides redhat-release >= 7 needed by epel-release-7-14.noarch
(try to add '--skip-broken' to skip uninstallable packages)

I need many tools, such as openjdk15 python2.7.18 that not in Amazon Linux 2022 repository. How to install these by yum install rather than source install.
How can I fix these problems to easy install extras tools or packages.
Look forward to your reply，ths!

**Comment by stewartsmith** [comment]
`amazon-linux-extras` is a facility unique to Amazon Linux 2, and is not present in Amazon Linux 2022.

We have several versions of Amazon Corretto available as a JVM, so one of those may be suitable for your JVM need.

We are not currently planning to ship a Python 2.7 in Amazon Linux 2022
