### ISSUE TITLE
[Feature Request] - AL2022 Container Images

### ISSUE THREAD

**Issue by stewartsmith** [amazonlinux/amazon-linux-2022#2]
**Is your feature request related to a problem? Please describe.**
Run Amazon Linux 2022 inside a container.

**Describe the solution you'd like**
Container images available on ECR and DockerHub the same time as AMIs

**Comment by stewartsmith** [comment]
Good news everyone!

https://docs.aws.amazon.com/linux/al2022/ug/install-docker.html is now up and so is the container image of AL2022!

**Comment by haisamido** [comment]
Using instructions from here https://docs.aws.amazon.com/linux/al2022/ug/install-docker.html 

When I do:

  `docker pull public.ecr.aws/amazonlinux/amazonlinux:2022`

and then

 ` docker run -it public.ecr.aws/amazonlinux/amazonlinux:2022 /bin/bash`

and when inside of the container I run `dnf update` I get this error

[root@bcab82f0f08b /]# dnf update                             
Amazon Linux 2022 repository                                                                                                                                                                                                         0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'amazonlinux':
  - Curl error (6): Couldn't resolve host name for https://al2022-repos-us-west-2-9761ab97.s3.dualstack.us-west-2.amazonaws.com/core/mirrors/2022.0.20211222/x86_64/mirror.list  [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'amazonlinux': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://al2022-repos-us-west-2-9761ab97.s3.dualstack.us-west-2.amazonaws.com/core/mirrors/2022.0.20211222/x86_64/mirror.list  [getaddrinfo() thread failed to start]
Ignoring repositories: amazonlinux
Dependencies resolved.
Nothing to do.
Complete!
