### ISSUE TITLE
[Bug] brltty-xw is not installable.

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#20]
**Describe the bug**
`dnf install brltty-xw` fails as `ucs-miscfixed-fonts` is not available in the package repositories.

**To Reproduce**
1. Try to `dnf install brltty-xw` on AL2022.

**Expected behavior**
`brltty-xw` is installed.

**Log**
```
$ sudo dnf install brltty-xw
Last metadata expiration check: 0:24:15 ago on Tue 23 Nov 2021 09:31:37 AM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides ucs-miscfixed-fonts needed by brltty-xw-6.3-1.amzn2022.x86_64
  - nothing provides ucs-miscfixed-fonts needed by brltty-xw-6.3-1.amzn2022.i686
(try to add '--skip-broken' to skip uninstallable packages)
```

**Additional context**
`ucs-miscfixed-fonts` is available in AL2.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request!  We are aware that the repositories are missing some runtime dependencies for existing packages.  As we rapidly iterate over the content in the next couple of weeks we will achieve full dependency closure.
