### ISSUE TITLE
[Package Request] - openssl-static (available on/for amazonlinux:2)

### ISSUE THREAD

**Issue by haisamido** [amazonlinux/amazon-linux-2022#216]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

>   `openssl-static` A statically compiled version of the openssl library

**Is this an update to existing package or new package request?**

>   A new package for amazonlinux:2022 but is available for amazonlinux:2

**Is this package available in Amazon Linux 2?**

> **Yes**. Needed for compilation of our c++ code base which processes telemetry, we need the `openssl-static` package. 

_Ideally the following would be the action needed to install the package_:

> `dnf -y install openssl-static`

**Number of users impacted**

> potentially 100+

**Comment by haisamido** [comment]
did this

`dnf -y install https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/35/Everything/x86_64/os/Packages/o/openssl-static-1.1.1l-2.fc35.x86_64.rpm`

and got this error:

```
Last metadata expiration check: 0:02:07 ago on Tue Nov  1 23:55:48 2022.
openssl-static-1.1.1l-2.fc35.x86_64.rpm                                                                                                                                                                                                                          364 kB/s | 1.8 MB     00:04    
Error: 
 Problem: conflicting requests
  - nothing provides openssl-devel(x86-64) = 1:1.1.1l-2.fc35 needed by openssl-static-1:1.1.1l-2.fc35.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by daniejstriata** [comment]
Can you install the package here?
https://koji.fedoraproject.org/koji/buildinfo?buildID=1997389

**Comment by daniejstriata** [comment]
I logged a ticket here:
https://bugzilla.redhat.com/show_bug.cgi?id=2139333
Let's see what they reply with.

**Comment by elsaco** [comment]
@haisamido during build static libraries are being remove, see `openssl.spec`:

```
283 # Remove static libraries
284 for lib in $RPM_BUILD_ROOT%{_libdir}/*.a ; do
285         rm -f ${lib}
286 done
```

To get the `openssl.src` package enable `amazon-source` in the repo list, run `dnf download --source openssl` and rebuild openssl to include the static libs also.

**Comment by stewartsmith** [comment]
We don't have any plans to ship static libraries for OpenSSL, and instead point towards dynamic linking to take advantage of the benefits a shared library provides: such as security updates without having to rebuild everything.
