### ISSUE TITLE
[Bug] dmraid-events-logwatch is not installable due to lack of logwatch

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#22]
**Describe the bug**
`dnf install dmraid-events-logwatch` fails as `logwatch` is not available in the package repositories.

**To Reproduce**
1. Try to `dnf install dmraid-events-logwatch` on AL2022.

**Expected behavior**
`dmraid-events-logwatch` is installed.

**Log**
```
$ sudo dnf install dmraid-events-logwatch.x86_64
Last metadata expiration check: 0:35:03 ago on Tue 23 Nov 2021 09:31:37 AM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides logwatch needed by dmraid-events-logwatch-1.0.0.rc16-50.amzn2022.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Additional context**
`logwatch` is available on AL2.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request!  We are aware that the repositories are missing some runtime dependencies for existing packages.  As we rapidly iterate over the content in the next couple of weeks we will achieve full dependency closure.
