### ISSUE TITLE
[Package Request] - EPEL 9

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2022#225]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
epel-release-9-4.el9.noarch

I cannot install EPEL 9 on AL2022 due to the following error:
`
yum install https://rpm.ocsinventory-ng.org/ocsinventory-release-latest.el9.ocs.noarch.rpm
`
```
epel-release-latest-9.noarch.rpm                                                                                  384 kB/s |  18 kB     00:00
Error:
 Problem: conflicting requests
  - nothing provides redhat-release >= 9 needed by epel-release-9-4.el9.noarch
```
**Is this an update to existing package or new package request?**
new

**Is this package available in Amazon Linux 2?**
Yes

**Number of users impacted**

**Comment by nmeyerhans** [comment]
Amazon Linux 2022 does not target compatibility with EPEL.
