### ISSUE TITLE
[Bug] dracut-squash is not installable due to lack squashfs-tools

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#23]
**Describe the bug**
`dnf install dracut-squash` fails as `squashfs-tools` is not available in the package repositories.

**To Reproduce**
1. Try to `dnf install dracut-squash` on AL2022.

**Expected behavior**
`dracut-squash` is installed.

**Log**
```
$ sudo dnf install dracut-squash.x86_64
Last metadata expiration check: 0:45:00 ago on Tue 23 Nov 2021 09:31:37 AM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides squashfs-tools needed by dracut-squash-055-6.amzn2022.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by stewartsmith** [comment]
We should have an update that fixes this out shortly.
