### ISSUE TITLE
[Bug] - /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by paulrutter** [amazonlinux/amazon-linux-2022#233]
When installing packages through yum, the warning about `setLocale` is shown.
This goes for other unix commands as well.

In AL2, it just worked to set the locale as environment variables like this (no warnings):

```
ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8"
```

Now it shows the following warning when running a `yum install` command:
```
RUN yum install -q -y https://rpm.nodesource.com/pub_18.x/el/8/x86_64/nodejs-18.12.1-1nodesource.x86_64.rpm
````

```
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8): No such file or directory
Failed to set locale, defaulting to C.UTF-8
```

**To Reproduce**
```
FROM amazonlinux:2022

ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8"

RUN yum install -q -y https://rpm.nodesource.com/pub_18.x/el/8/x86_64/nodejs-18.12.1-1nodesource.x86_64.rpm
```

It doesn't give the warning in al2:
```
FROM amazonlinux:2

ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8"

RUN yum install -q -y https://rpm.nodesource.com/pub_18.x/el/8/x86_64/nodejs-18.12.1-1nodesource.x86_64.rpm
```

**Expected behavior**
Locale is set properly, no warning is shown.

**Additional context**
Using latest AL2022 Docker image.

**Comment by pluralistix** [comment]
Not sure, if that is/was clear already (if, I do apologize for interfering), but glibc-langpack-en, which came with AL2 is not included in AL2022 anymore. It can be installed, of course.

```
docker run amazonlinux:2 rpm -q glibc-langpack-en
glibc-langpack-en-2.26-62.amzn2.x86_64
```

```
docker run amazonlinux:2022 rpm -q glibc-langpack-en
package glibc-langpack-en is not installed
```

**Comment by paulrutter** [comment]
Thanks for the information, i will look into it to see if that solves the issue.

**Comment by paulrutter** [comment]
```
FROM amazonlinux:2022

RUN yum install -q -y glibc-langpack-en

ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8"

RUN yum install -q -y https://rpm.nodesource.com/pub_18.x/el/8/x86_64/nodejs-18.12.1-1nodesource.x86_64.rpm
```

Indeed seems to fix the warning.
I thought i tried that already, but apparently not. Thanks for the help!
