### ISSUE TITLE
[Bug] Some packages are not installable due to lack of libsrtp2.so.1.

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#24]
**Describe the bug**
These packages are not installable as `libsrtp2.so.1` is not available in the package repositories.

```
gstreamer1-plugins-bad-free.x86_64
gstreamer1-plugins-bad-free-devel.x86_64
gtk4.x86_64
gtk4-devel.x86_64
gtk4-devel-docs.x86_64
ibus-gtk4.x86_64
```

**To Reproduce**
1. Try to `dnf install gstreamer1-plugins-bad-free` on AL2022.

**Expected behavior**
`gstreamer1-plugins-bad-free` is installed.

**Log**
```
$ sudo dnf install gstreamer1-plugins-bad-free.x86_64
Last metadata expiration check: 1:06:26 ago on Tue 23 Nov 2021 09:31:37 AM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides libsrtp2.so.1()(64bit) needed by gstreamer1-plugins-bad-free-1.19.1-3.1.18.4.amzn2022.0.1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Additional context**
`libsrtp.so.0` (not libsrtp_2_) is available on AL2.
```
$ sudo yumdownloader libsrtp
$ rpm -q -l -p ./libsrtp-1.4.4-11.20101004cvs.amzn2.x86_64.rpm 
/usr/lib64/libsrtp.so.0
...
```

**Comment by liesenml** [comment]
Hello, thank you for submitting your request!  We are aware that the repositories are missing some runtime dependencies for existing packages.  As we rapidly iterate over the content in the next couple of weeks we will achieve full dependency closure.
