### ISSUE TITLE
[Bug] - Elastic Beanstalk cannot use latest kernel 5.10 AMI's due to RPM dependency chain issues

### ISSUE THREAD

**Issue by gregnetau** [amazonlinux/amazon-linux-2022#242]
**Describe the bug**

**To Reproduce**
1. Go to AWS Elastic Beanstalk
2. Click on Deploy a sample PHP application
3. After deployment, change the "default" AMI provided, to the latest one available 

```
[root@host ~]# cat /etc/image-id
image_name="amzn2-ami-hvm"
image_version="2"
image_arch="x86_64"
image_file="amzn2-ami-hvm-2.0.20221004.0-x86_64.xfs.gpt"
image_stamp="0451-36e9"
image_date="20221012185818"
recipe_name="amzn2 ami"
recipe_id="d2ea3ac7-5445-1ea6-7f57-b522-e039-da86-1cf7213a"
[root@host ~]# uname -a
Linux host 4.14.294-220.533.amzn2.x86_64 SMP Thu Sep 29 01:01:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

4. Elastic Beanstalk will get stuck on a loop trying to install gcc

**Expected behavior**
Elastic Beanstalk should build using the latest linux AMI's

**Log**

**Comment by wehfmm** [comment]
Amazon Linux 2022 has kernel 5.15 series since RC0.
https://docs.aws.amazon.com/linux/al2022/release-notes/relnotes-20221103.html#major-changes-20221103
```
Kernel updated from 5.10 to 5.15
```

> [root@host ~]# uname -a
> Linux host 4.14.294-220.533.amzn2.x86_64 SMP Thu Sep 29 01:01:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

"amzn2" is Amazon Linux 2, not Amazon Linux 2022. I think this issue is not Amazon Linux 2022, but AWS Elastic Beanstalk.

**Comment by daniejstriata** [comment]
trying `glibc-2.26-61.amzn2.i686` looks suspect.

**Comment by nmeyerhans** [comment]
> Is there actually an AMZN2 GH repo?

Not at this time, but the "Questions" section of re:Post is a good place for this kind of issue: https://repost.aws/questions
