### ISSUE TITLE
[Bug] gvfs-afc is not installable due to lack of usbmuxd.

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#25]
**Describe the bug**
`dnf install gvfs-afc.x86_64` fails as `usbmuxd` is not available in the package repositories.

**To Reproduce**
1. Try to `dnf install gvfs-afc.x86_64` on AL2022.

**Expected behavior**
`gvfs-afc.x86_64` is installed.

**Log**
```
$ sudo dnf install gvfs-afc.x86_64
Last metadata expiration check: 0:00:01 ago on Tue 23 Nov 2021 10:41:30 AM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides usbmuxd needed by gvfs-afc-1.48.1-1.amzn2022.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Additional context**
`usbmuxd` is available on AL2.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request!  We are aware that the repositories are missing some runtime dependencies for existing packages.  As we rapidly iterate over the content in the next couple of weeks we will achieve full dependency closure.
