### ISSUE TITLE
[Package Request] - mysql

### ISSUE THREAD

**Issue by jbergman-apiture** [amazonlinux/amazon-linux-2022#257]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
mysql package is missing from the al2022 repo.  al2 calls mariadb.  This is also not available.

**Is this an update to existing package or new package request?**
new package request

**Is this package available in Amazon Linux 2?**
Yes as mariadb
Id like either to see mysql or mariadb offered for al2022

**Number of users impacted**
A lot people looking for mysql connectivity.

**Comment by stewartsmith** [comment]
MariaDB 10.5 is available in AL2022, it’s just namespaced as mariadb105Sent from my iPhoneOn Jan 9, 2023, at 12:10 PM, Josh Bergman ***@***.***> wrote:﻿
What package is missing from Amazon Linux 2022? Please describe and include package name.
mysql package is missing from the al2022 repo.  al2 calls mariadb.  This is also not available.
Is this an update to existing package or new package request?
new package request
Is this package available in Amazon Linux 2?
Yes as mariadb
A clear and concise description of what you want to happen.
Id like either to see mysql or mariadb offered for al2022
Number of users impacted
A lot people looking for mysql connectivity.

**Comment by jbergman-apiture** [comment]
Can confirm this is what I was looking for.  Appreciate the reply.  will close.
