### ISSUE TITLE
[Bug] ibus is not installable due to lack of setxkbmap

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#26]
**Describe the bug**
`dnf install ibus.x86_64 ibus-tests.x86_64` fails as `setxkbmap` is not available in the package repositories.

**To Reproduce**
1. Try to `dnf install ibus.x86_64 ibus-tests.x86_64` on AL2022.

**Expected behavior**
`ibus.x86_64` and `ibus-tests.x86_64` is installed.

**Log**
```
$ sudo dnf install ibus.x86_64 ibus-tests.x86_64
Last metadata expiration check: 0:03:04 ago on Tue 23 Nov 2021 02:26:30 PM UTC.
Error: 
 Problem 1: conflicting requests
  - nothing provides setxkbmap needed by ibus-1.5.24-5.amzn2022.x86_64
 Problem 2: package ibus-tests-1.5.24-5.amzn2022.x86_64 requires ibus(x86-64) = 1.5.24-5.amzn2022, but none of the providers can be installed
  - conflicting requests
  - nothing provides setxkbmap needed by ibus-1.5.24-5.amzn2022.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by liesenml** [comment]
Hello, thank you for submitting your request!  We are aware that the repositories are missing some runtime dependencies for existing packages.  As we rapidly iterate over the content in the next couple of weeks we will achieve full dependency closure.
