### ISSUE TITLE
[Package Request] - OpenZFS 2

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2022#262]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
OpenZFS - https://openzfs.github.io/openzfs-docs/Getting%20Started/Fedora/index.html

**Is this an update to existing package or new package request?**
New

**Is this package available in Amazon Linux 2?**
I need to test ZFS on AL2022 and would like to use it but the official version is reliant on EPEL

**Number of users impacted**
N/A

**Comment by daniejstriata** [comment]
I installed OpenZFS using the FC37 repo. I enabled to module and it seems to work fine.

**Comment by stewartsmith** [comment]
This is not something we can consider until OpenZFS is in the upstream Linux kernel. Unfortunately, this is effectively saying that OpenZFS for Amazon Linux won't happen.
