### ISSUE TITLE
Unable to add Remi Repo for Amazon Linux 2 

### ISSUE THREAD

**Issue by raunak-vm** [amazonlinux/amazon-linux-2022#265]
I have to install older versions of php and I am unable to do so through amazpn-linux-extras, I need remi repo for Amazon LInux 2 and I am unable to change php version from repo after adding to my linux instance

**Comment by stewartsmith** [comment]
What versions of PHP are you looking for?Sent from my iPhoneOn Jan 30, 2023, at 9:32 PM, Raunak Kumar ***@***.***> wrote:﻿
I have to install older versions of php and I am unable to do so through amazpn-linux-extras, I need remi repo for Amazon LInux 2 and I am unable to change php version from repo after adding to my linux instance

**Comment by raunak-vm** [comment]
I was looking for php7.3 and 7.4, and from amazon-linux-extras package I am unable to install some php-extensions in the version 8.0.

**Comment by raunak-vm** [comment]
Error message 
Problem : I was changing php version from 7.4 to 8.1 and I also want to install php-extensions with php8.1 version, but I am unable to do so. I have installed php from amazon-linux-extras package . 

Error: Package: php-xmlrpc-5.4.16-46.amzn2.0.2.x86_64 (amzn2-core)
           Requires: php-common(x86-64) = 5.4.16-46.amzn2.0.2
           Installed: php-common-8.1.12-1.amzn2.x86_64 (@amzn2extra-php8.1)
               php-common(x86-64) = 8.1.12-1.amzn2
           Available: php-common-5.4.16-43.amzn2.x86_64 (amzn2-core)
               php-common(x86-64) = 5.4.16-43.amzn2
           Available: php-common-5.4.16-43.amzn2.0.1.x86_64 (amzn2-core)
               php-common(x86-64) = 5.4.16-43.amzn2.0.1
           Available: php-common-5.4.16-43.amzn2.0.2.x86_64 (amzn2-core)
               php-common(x86-64) = 5.4.16-43.amzn2.0.2
           Available: php-common-5.4.16-43.amzn2.0.3.x86_64 (amzn2-core)
               php-common(x86-64) = 5.4.16-43.amzn2.0.3
           Available: php-common-5.4.16-43.amzn2.0.4.x86_64 (amzn2-core)
               php-common(x86-64) = 5.4.16-43.amzn2.0.4
           Available: php-common-5.4.16-45.amzn2.0.5.x86_64 (amzn2-core)
               php-common(x86-64) = 5.4.16-45.amzn2.0.5
           Available: php-common-5.4.16-45.amzn2.0.6.x86_64 (amzn2-core)
               php-common(x86-64) = 5.4.16-45.amzn2.0.6
           Available: php-common-5.4.16-46.amzn2.0.2.x86_64 (amzn2-core)
               php-common(x86-64) = 5.4.16-46.amzn2.0.2
           Available: php-common-8.1.11-1.amzn2.x86_64 (amzn2extra-php8.1)
               php-common(x86-64) = 8.1.11-1.amzn2
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest


php-pdo is available in Amazon Linux Extra topic "php8.0"

To use, run
# sudo amazon-linux-extras install php8.0

php-fpm is available in Amazon Linux Extra topic "php8.0"

To use, run
# sudo amazon-linux-extras install php8.0

php-mysqlnd is available in Amazon Linux Extra topic "php8.0"

To use, run
# sudo amazon-linux-extras install php8.0

Learn more at
https://aws.amazon.com/amazon-linux-2/faqs/#Amazon_Linux_Extras    
![image](https://user-images.githubusercontent.com/121629263/215761381-194b20ba-411d-4a57-81fd-75f3c120fb42.png)

**Comment by stewartsmith** [comment]
There are older and unsupported versions of PHP available in AL2 Extras, but are hidden by the UI due to being EoL.
