### ISSUE TITLE
[Bug] - Minimum storage allowed for / is 30Gb

### ISSUE THREAD

**Issue by daniejstriata** [amazonlinux/amazon-linux-2022#268]
**Describe the bug**
I tried both the X86_64 and ARM images and found I am forced to use 30Gb for / or larger

Exact image tried: 
al2022-ami-ecs-hvm-2022.0.20220630-x86_64-ebs
ami-05ae943394d2ed741
al2022-ami-ecs-hvm-2022.0.20221102-kernel-5.15-arm64
ami-03c3fe63ff93c789e
**To Reproduce**
When selecting a size smaller than 30Gb I am presented with
"Volume is smaller than snapshot, must be at least 30."

**Expected behavior**
I am able to create volumes of around 8Gb on AMZN2
**Screenshots**
![image](https://user-images.githubusercontent.com/13314239/218761948-54d69b6e-92c5-4dea-a483-ea75130609d6.png)

**Desktop (please complete the following information):**
AL2022

**Additional context**
Note that there are 2 images available to select from. The one for ARM64 seems to be a much newer build than x86_64, both being version 1.1.

**Comment by stewartsmith** [comment]
`2022.0.20230118` at least is happy with 8GB volumes... please reopen if still seeing this issue.
