### ISSUE TITLE
[Bug] icedax is not installable due to lack of vorbis-tools

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#27]
**Describe the bug**
`dnf install icedax` fails as `vorbis-tools` is not available in the package repositories.

**To Reproduce**
1. Try to `dnf install icedax` on AL2022.

**Expected behavior**
`icedax` is installed.

**Log**
```
$ sudo dnf install icedax
Last metadata expiration check: 0:04:04 ago on Tue 23 Nov 2021 02:26:30 PM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides vorbis-tools needed by icedax-1.1.11-47.amzn2022.x86_64
  - nothing provides vorbis-tools needed by icedax-1.1.11-47.amzn2022.i686
(try to add '--skip-broken' to skip uninstallable packages)
```

**Additional context**
`vorbis-tools` is available on AL2.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request!  We are aware that the repositories are missing some runtime dependencies for existing packages.  As we rapidly iterate over the content in the next couple of weeks we will achieve full dependency closure.
