### ISSUE TITLE
[Feature Request] - Want to have PSI

### ISSUE THREAD

**Issue by gavin-jeong** [amazonlinux/amazon-linux-2022#271]
https://docs.kernel.org/accounting/psi.html

Seems it is disabled by default.

```bash
$ cat /boot/config-5.15.73-45.135.amzn2022.aarch64 | grep -i PSI
CONFIG_PSI=y
CONFIG_PSI_DEFAULT_DISABLED=y
```

**Comment by daniejstriata** [comment]
add `psi=1 `to `GRUB_CMDLINE_LINUX` inside `/etc/default/grub`. Then run 
`grub2-mkconfig -o /boot/grub2/grub.cfg`
When you reboot you'll see
```
CONFIG_PSI=y
CONFIG_PSI_DEFAULT_DISABLED=y
```
did not change but you have access to PSI.

**Comment by sj-aws** [comment]
We also enabled it by default since kernel-6.1.19-30.43.amzn2023.
