### ISSUE TITLE
[Bug] inkscape is not installable due to lack of libpotrace.so.0.

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#28]
**Describe the bug**
`dnf install inkscape` fails as `libpotrace.so.0` is not available in the package repositories.

**To Reproduce**
1. Try to `dnf install inkscape` on AL2022.

**Expected behavior**
`inkscape` is installed.

**Log**
```
$ sudo dnf install inkscape.x86_64 inkscape-view.x86_64
Last metadata expiration check: 0:06:21 ago on Tue 23 Nov 2021 02:26:30 PM UTC.
Error: 
 Problem 1: conflicting requests
  - nothing provides libpotrace.so.0()(64bit) needed by inkscape-1.0.2-2.amzn2022.x86_64
 Problem 2: conflicting requests
  - nothing provides libpotrace.so.0()(64bit) needed by inkscape-view-1.0.2-2.amzn2022.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by liesenml** [comment]
Hello, thank you for submitting your request!  We are aware that the repositories are missing some runtime dependencies for existing packages.  As we rapidly iterate over the content in the next couple of weeks we will achieve full dependency closure.
