### ISSUE TITLE
[Feature Request] - AL2022 as container host

### ISSUE THREAD

**Issue by stewartsmith** [amazonlinux/amazon-linux-2022#3]
**Is your feature request related to a problem? Please describe.**
Using Amazon Linux 2022 as the host to run containers in the same way that one can use Amazon Linux 1 and Amazon Linux 2 to.

**Describe the solution you'd like**
Docker and related packages available in the AL2022 repositories.

**Comment by StephenGennard** [comment]
@stewartsmith Can you consider OCI tooling (podman/buildah) please?

**Comment by samuelkarp** [comment]
Hey @StephenGennard!  Just to wear my [OCI Technical Oversight Board](https://opencontainers.org/about/tob/) hat for a minute:

You can find the full set of OCI projects [in the opencontainers GitHub organization](https://github.com/opencontainers/).  Podman and Buildah are not OCI projects and (based on the [list of maintainers for Buildah](https://github.com/containers/buildah/blob/main/MAINTAINERS)) they appear to be Red Hat projects.

Putting my Amazon hat back on: Thanks for the package request!  As we are considering the specific packages we'd like to include for Amazon Linux 2022 container support, we'd love to find out more about your preferences for specific container tooling.  In Amazon Linux 1 and Amazon Linux 2 we've included packages for Docker, containerd, and runc and our partner teams inculding [AWS Fargate](https://aws.amazon.com/blogs/containers/under-the-hood-fargate-data-plane/), [Amazon EKS](https://aws.amazon.com/blogs/containers/amazon-eks-1-21-released/), and [Bottlerocket](https://github.com/bottlerocket-os/bottlerocket) have moved toward containerd.  However, if you have preferences for other tooling (such as Buildah and Podman) we'd appreciate your feeback.

**Comment by StephenGennard** [comment]
> Hey @StephenGennard! Just to wear my OCI Technical Oversight Board hat for a minute:
> You can find the full set of OCI projects in the opencontainers GitHub organization. Podman and Buildah are not OCI projects and (based on the list of maintainers for Buildah) they appear to be Red Hat projects.

Thanks for the clarification.

The choice of tooling for building from our perspective is either "docker build" or Buildah, as we currently from Dockerfile/Containerfile's.

Our preference for execution is podman/rootless with pods, which for us, gives us a lightweight container solution without getting into the complexities of Kubernetes.

Rootless mode gives us per-user isolation, which allows us to keep development away from qa/testing with ease.


________________________________

**Comment by skyzyx** [comment]
Related: My company does a lot with ECS-on-EC2. Is it reasonable to expect that there will be an _ECS-optimized_ AMI built atop AL2022 at some point in the future?

(This feels like the same topic, but if you feel this is a different topic, let me know and I'll file a new issue.)

**Comment by stewartsmith** [comment]
> Related: My company does a lot with ECS-on-EC2. Is it reasonable to expect that there will be an _ECS-optimized_ AMI built atop AL2022 at some point in the future?
> 
> (This feels like the same topic, but if you feel this is a different topic, let me know and I'll file a new issue.)

It is a reasonable expectation. I'm not sure if it's best to track the availability in an issue here or over at https://github.com/aws/containers-roadmap - I'll poke some people on the ECS team to ask their preference.

**Comment by stewartsmith** [comment]
Since `docker` is in the Amazon Linux 2022 repos, and can run as a container host, I'm going to close this issue out as fixed.

**Comment by stewartsmith** [comment]
> It is a reasonable expectation. I'm not sure if it's best to track the availability in an issue here or over at https://github.com/aws/containers-roadmap - I'll poke some people on the ECS team to ask their preference.

The Containers Roadmap project is the best one to file an issue with so it's easily tracked.
