### ISSUE TITLE
[Bug] kernel-livepatch is not installable due to lack of kpatch

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#30]
**Describe the bug**
`dnf install kernel-livepatch-5.10.75-82.359.x86_64` fails as `kpatch` is not available in the package repositories.

**To Reproduce**
1. Try to `dnf install kernel-livepatch-5.10.75-82.359.x86_64` on AL2022.

**Expected behavior**
`kernel-livepatch-5.10.75-82.359.x86_64` is installed.

**Log**
```
$ sudo dnf install kernel-livepatch-5.10.75-82.359.x86_64
Last metadata expiration check: 0:12:33 ago on Tue 23 Nov 2021 02:26:30 PM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides kpatch needed by kernel-livepatch-5.10.75-82.359-1.0-0.amzn2022.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Additional context**
`kpatch` is available on AL2.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request!  We are aware that the repositories are missing some runtime dependencies for existing packages.  As we rapidly iterate over the content in the next couple of weeks we will achieve full dependency closure.
