### ISSUE TITLE
[crontab] - After installing crontab not found

### ISSUE THREAD

**Issue by pareshcc** [amazonlinux/amazon-linux-2022#302]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

**Is this an update to existing package or new package request?**

**Is this package available in Amazon Linux 2? If it is available via external sources such as EPEL, please specify.**

**Any additional information you'd like to include. (use-cases, etc)**

**Comment by nmeyerhans** [comment]
Resolving as a duplicate of #300
