### ISSUE TITLE
[Bug] libinput-utils is not installable due to lack of python3-libevdev

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#31]
**Describe the bug**
`dnf install libinput-utils` fails as `python3-libevdev` is not available in the package repositories.

**To Reproduce**
1. Try to `dnf install libinput-utils` on AL2022.

**Expected behavior**
`libinput-utils` is installed.

**Log**
```
$ sudo dnf install libinput-utils.x86_64
Last metadata expiration check: 0:18:29 ago on Tue 23 Nov 2021 02:26:30 PM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides python3-libevdev needed by libinput-utils-1.19.2-1.amzn2022.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by liesenml** [comment]
Hello, thank you for submitting your request!  We are aware that the repositories are missing some runtime dependencies for existing packages.  As we rapidly iterate over the content in the next couple of weeks we will achieve full dependency closure.
