### ISSUE TITLE
[Bug] libproxy-kde is not installable due to lack of /usr/bin/kreadconfig5

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#32]
**Describe the bug**
`dnf install libproxy-kde.x86_64` fails as `/usr/bin/kreadconfig5` is not available in the package repositories.

**To Reproduce**
1. Try to `dnf install libproxy-kde.x86_64` on AL2022.

**Expected behavior**
`libproxy-kde.x86_64` is installed.

**Log**
```
$ sudo dnf install libproxy-kde.x86_64
Last metadata expiration check: 0:22:13 ago on Tue 23 Nov 2021 02:26:30 PM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides /usr/bin/kreadconfig5 needed by libproxy-kde-0.4.15-30.amzn2022.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by liesenml** [comment]
Hello, thank you for submitting your request!  We are aware that the repositories are missing some runtime dependencies for existing packages.  As we rapidly iterate over the content in the next couple of weeks we will achieve full dependency closure.
