### ISSUE TITLE
[Bug] libproxy-pacrunner is not installable due to lack of pacrunner.

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#33]
**Describe the bug**
`dnf install libproxy-pacrunner` fails as `pacrunner` is not available in the package repositories.

**To Reproduce**
1. Try to `dnf install libproxy-pacrunner` on AL2022.

**Expected behavior**
`libproxy-pacrunner` is installed.

**Log**
```
$ sudo dnf install libproxy-pacrunner
Last metadata expiration check: 0:23:25 ago on Tue 23 Nov 2021 02:26:30 PM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides pacrunner needed by libproxy-pacrunner-0.4.15-30.amzn2022.x86_64
  - nothing provides pacrunner needed by libproxy-pacrunner-0.4.15-30.amzn2022.i686
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by liesenml** [comment]
Hello, thank you for submitting your request!  We are aware that the repositories are missing some runtime dependencies for existing packages.  As we rapidly iterate over the content in the next couple of weeks we will achieve full dependency closure.
