### ISSUE TITLE
[Bug] libreport-plugin-mailx is not installable due to lack of /usr/bin/mailx.

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#34]
**Describe the bug**
`dnf install libreport-plugin-mailx` fails as `/usr/bin/mailx` is not available in the package repositories.

**To Reproduce**
1. Try to `dnf install libreport-plugin-mailx` on AL2022.

**Expected behavior**
`libreport-plugin-mailx` is installed.

**Log**
```
$ sudo dnf install libreport-plugin-mailx
Last metadata expiration check: 0:25:11 ago on Tue 23 Nov 2021 02:26:30 PM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides /usr/bin/mailx needed by libreport-plugin-mailx-2.15.2-2.amzn2022.x86_64
  - nothing provides /usr/bin/mailx needed by libreport-plugin-mailx-2.15.2-2.amzn2022.i686
(try to add '--skip-broken' to skip uninstallable packages)
```

**Additional context**
`/bin/mailx` is available on AL2.

```
$ sudo yum provides *mailx*
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
mailx-12.5-16.amzn2.x86_64 : Enhanced implementation of the mailx command
Repo        : amzn2-core
Matched from:
...
Filename    : /bin/mailx
...
```

**Comment by liesenml** [comment]
Hello, thank you for submitting your request!  We are aware that the repositories are missing some runtime dependencies for existing packages.  As we rapidly iterate over the content in the next couple of weeks we will achieve full dependency closure.
