### ISSUE TITLE
[Bug] - Loading tcm_loop.ko kernel module fails

### ISSUE THREAD

**Issue by yorickdowne** [amazonlinux/amazon-linux-2022#38]
**Describe the bug**

Attempting to load the `tcm_loop.ko` kernel module fails with error message `Unknown symbol in module`

**To Reproduce**

Run `sudo insmod /lib/modules/5.10.75-82.359.amzn2022.x86_64/kernel/drivers/target/loopback/tcm_loop.ko`

**Comment by stewartsmith** [comment]
At least with `al2022-ami-2022.0.20230118.3-kernel-5.15-x86_64` this is no longer the case, so has been fixed.
