### ISSUE TITLE
[Feature Request] - Add `target_core_user` kernel module

### ISSUE THREAD

**Issue by yorickdowne** [amazonlinux/amazon-linux-2022#39]
**Describe the solution you'd like**

In order to support the OnDat Kubernetes storage provider with TCMU/LIO, please add the `target_core_user.ko` kernel module.

OnDat requires these kernel modules for maximum performance:
```
target_core_mod
tcm_loop
target_core_file
configfs
target_core_user
uio
```

All but `target_core_user` ship with AL2022. A [separate issue](https://github.com/amazonlinux/amazon-linux-2022/issues/38) has been opened for `tcm_loop` not loading successfully.

**Comment by stewartsmith** [comment]
The `target_core_user` module is now built, and is available in current Amazon Linux 2022 repositories.
