### ISSUE TITLE
[Package Request] - dnf repo-versions

### ISSUE THREAD

**Issue by vchepkov** [amazonlinux/amazon-linux-2022#40]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

Amazon Linux 2022 FAQ mentions ` dnf repo-versions list` command, but it fails and attempts to install it with `dnf install 'dnf-command(repo-versions)` fails as well

**Comment by stewartsmith** [comment]
Yes, this appears to be a mismatch between current documentation and current DNF plugin functionality for our version locking feature. We'll work on removing this mismatch.

**Comment by stewartsmith** [comment]
https://docs.aws.amazon.com/linux/al2022/ug/managing-repos-os-updates.html has the updated commands.
