### ISSUE TITLE
dnf annoyance

### ISSUE THREAD

**Issue by elsaco** [amazonlinux/amazon-linux-2022#41]
**Describe the bug**
DNF keeps showing warning after applying latest release update. 

**To Reproduce**
1. refresh dnf cache
2. update to latest release: `sudo dnf update --releasever=2022.0.20211124`
3. install new package(s)
4. See dnf warning

**Expected behavior**
-no more update warning after applying latest release.

**Sample log**
-after installing a new package
```
WARNING:
  A newer release of "Amazon Linux" is available.

  Available Versions:

  Version 2022.0.20211124:
    Run the following command to update to 2022.0.20211124:

      dnf update --releasever=2022.0.20211124

    Release notes:
     https://aws.amazon.com
```

**Additional context**
-release update was applied several times, followed by instance reboots.

**Comment by stewartsmith** [comment]
There was a bug in our process of pushing out 2022.0.20211124, and will be looking to fix this up soon.

**Comment by crabby345** [comment]
I was having to specify releasever on every call to dnf. Is that a bug then? Should only be required once?

**Comment by edwardvdv** [comment]
I can confirm this bug is fixed with the new system-release package in the `2022.0.20211201` version:
```
13:57 ★root(su)@test-al2022 ~
0» rpm -q system-release --qf '%{version}'
2022.0.20211201

13:57 ★root(su)@test-al2022 ~
0» dnf check-release-update

# ^ note no output :-)
```

**Comment by PhilipPeake** [comment]
This problem is back.
`A newer release of "Amazon Linux" is available.
  Version 2023.1.20230906:
Run "/usr/bin/dnf check-release-update" for full release and version update info`

**Comment by stewartsmith** [comment]
your `system-release` package is at version `2023.1.20230906` ?

**Comment by PhilipPeake** [comment]
rpm -q system-release --qf '%{version}'
2023.1.20230906

**Comment by stewartsmith** [comment]
Okay, so this is probably just the `update-motd.service` not having run yet. It's set up to run daily and on boot (see https://github.com/amazonlinux/update-motd/blob/main/update-motd.service ).

Running it manually will fix the message.

Arguably what we should do in this case, where a reboot has not occurred, is to have worked out if a reboot is required to apply some updates or not, and point out if so.

**Comment by PhilipPeake** [comment]
I rebooted - message is gone.
I should have thought of that ...

Philip

**Comment by stewartsmith** [comment]
I've opened https://github.com/amazonlinux/amazon-linux-2023/issues/441 for this rather than reopening this issue, just so that it's a nice and clean description and history on the issue.

Thanks for helping confirm my suspicion there so quickly!
