### ISSUE TITLE
[Feature Request] - "Versionless" repository option

### ISSUE THREAD

**Issue by Conan-Kudo** [amazonlinux/amazon-linux-2022#44]
**Is your feature request related to a problem? Please describe.**
The Amazon Linux 2022 repositories are versioned such that repository contents are effectively locked to snapshot releases of AL2022 content. This makes things less than pleasant for building continuously updating AMIs and building packages against AL2022.

**Describe the solution you'd like**
I'd like to see a `2022` release version that always points to the latest repository content for AL2022.

**Describe alternatives you've considered**
I've considered tracking the versions and trying to ensure we update things on a regular basis. The problem with that is that as usage grows and more stakeholders build on top, there will be more touch points to update and it becomes a risky proposition to ensure that we're using the right content.

**Additional context**
Having versionless repositories would make it possible for Amazon Linux 2022 to be supported in the [openSUSE Build Service](https://build.opensuse.org/) and [Fedora Copr](https://copr.fedorainfracloud.org/), which are tools that I use for building stuff for Linux distributions for me and others to use.

**Comment by stewartsmith** [comment]
Is there a way where what repo is used could be bumped up regularly and automatically instead?

The benefit of that would be that you'd be certain what was built with what, and be able to control when things moved (and didn't).

We will consider a "latest" mirror list too though, as it's useful for some automation.

**Comment by Conan-Kudo** [comment]
It is not technically possible with Mock config or OBS distribution configuration in any reasonable way that I know of.

**Comment by stewartsmith** [comment]
We now have a `latest` mirror list, so with `--releasever=latest`, `dnf` will pull whatever is the release we have marked as the latest for the major version of the OS.

The AL2022 GPG key is in `distribution-gpg-keys` as of https://github.com/xsuchy/distribution-gpg-keys/pull/69 and all that's left now is to send a PR with a mock config, which I'll do shortly.
