### ISSUE TITLE
[Feature Request] - Kernel Live Patching

### ISSUE THREAD

**Issue by stewartsmith** [amazonlinux/amazon-linux-2022#5]
Support kernel live patches, like we do with Amazon Linux 2.

Depends on moving to 5.15: https://github.com/amazonlinux/amazon-linux-2022/issues/4

**Comment by jeroenhabets** [comment]
@stewartsmith (@liesenml) FWIW #4 has been Closed for a while now (by @njacklin1988 in Feb'22)

**Comment by stewartsmith** [comment]
`/etc/yum.repos.d/kernel-livepatch.repo` is present in modern AMIs, going to resolve this.
