### ISSUE TITLE
[Package Request] - conntrack-tools

### ISSUE THREAD

**Issue by ripta** [amazonlinux/amazon-linux-2022#55]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
`conntrack-tools` to manipulate netfilter conntrack table

**Is this an update to existing package or new package request?**
This is a new package request.

**Is this package available in Amazon Linux 2?**
Yes, it's available as conntrack-tools in AL2. Snippet from `yum info` on an AL2 machine:

```
root@ip-10-20-192-163 ~]# yum info conntrack-tools
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Installed Packages
Name        : conntrack-tools
Arch        : x86_64
Version     : 1.4.4
Release     : 5.amzn2.2
Size        : 536 k
Repo        : installed
From repo   : amzn2-core
Summary     : Manipulate netfilter connection tracking table and run High Availability
URL         : http://netfilter.org
License     : GPLv2
```

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by stewartsmith** [comment]
Teh `conntrack-tools` package is part of the `2022.0.20220728` release (possibly an earlier one too, but certainly in this release)
