### ISSUE TITLE
[Package Request] - container-selinux

### ISSUE THREAD

**Issue by ripta** [amazonlinux/amazon-linux-2022#56]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
`container-selinux`, which provides SELinux policies for container runtimes

**Is this an update to existing package or new package request?**
This is a new package request.

**Is this package available in Amazon Linux 2?**
No, container-selinux isn't available on AL2, but AL2 runs with SELinux disabled by default. On the other hand, AL2022 runs with SELinux enabled and enforcing by default.

**Comment by edwardvdv** [comment]
👍 Was about to open a new issue when I saw this. I completely agree, this is essential to make containerized workloads run in an SELinux enabled environment.

**Comment by stewartsmith** [comment]
Naturally, this is a part of implementing https://github.com/amazonlinux/amazon-linux-2022/issues/3 - but it's probably worthwhile we keep this open tracking the `container-selinux` package itself'

**Comment by samuelkarp** [comment]
> No, container-selinux isn't available on AL2, but AL2 runs with SELinux disabled by default.

Hi @ripta!  Just for completeness here: `container-selinux` is available in the Amazon Linux 2 `selinux-ng` Extra.  You can enable the Extra and install the package as follows:

```
# amazon-linux-extras enable selinux-ng
# yum install container-selinux
```

**Comment by stewartsmith** [comment]
```
bash-5.1# dnf info container-selinux
Last metadata expiration check: 4:03:05 ago on Fri Nov  4 16:47:43 2022.
Available Packages
Name         : container-selinux
Epoch        : 2
Version      : 2.189.0
Release      : 287.amzn2022
Architecture : noarch
Size         : 52 k
Source       : container-selinux-2.189.0-287.amzn2022.src.rpm
Repository   : amazonlinux
Summary      : SELinux policies for container runtimes
URL          : https://github.com/containers/container-selinux
License      : GPLv2
Description  : SELinux policy modules for use with container runtimes.

```

this is now in AL2022
