### ISSUE TITLE
[Package Request] - Cloudwatch Logs daemon

### ISSUE THREAD

**Issue by edwardvdv** [amazonlinux/amazon-linux-2022#59]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
`awslogs`

```
al2-instance » yum search awslogs
Loaded plugins: dkms-build-requires, extras_suggestions, langpacks, priorities, update-motd
212 packages excluded due to repository priority protections
===================================================================================================== N/S matched: awslogs =====================================================================================================
awslogs.noarch : Scripts for CloudWatch Logs Daemon
```

**Is this an update to existing package or new package request?**
No.

**Is this package available in Amazon Linux 2?**
Yes.

**Comment by petercooperjr** [comment]
I don't know if this is exactly the same package or not, but I was also expecting "amazon-cloudwatch-agent" to be available, in order to send logs and metrics to Cloudwatch.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by crabby345** [comment]
I thought aws-logs was legacy, superceded by amazon-cloudwatch-agent which isn't installed natively on al2, I install it via commandline or systems manager.

Would be useful as a repo package, as would awscli and a few others, but I don't think it's lost functionality (like ssm agent installed out of the box is).

**Comment by stewartsmith** [comment]
As of our 2022.0.20220628 release, there is the `amazon-cloudwatch-agent` available in the repositories.

We will have new AMIs and container images shortly, but in the meantime you can update with `dnf update --releasever=2022.0.20220628`

```
bash-5.1# dnf info amazon-cloudwatch-agent
Last metadata expiration check: 0:29:45 ago on Fri Jul  1 15:37:14 2022.
Available Packages
Name         : amazon-cloudwatch-agent
Version      : 1.247353.0_4_g9be43599
Release      : 1.amzn2022
Architecture : x86_64
Size         : 45 M
Source       : amazon-cloudwatch-agent-1.247353.0_4_g9be43599-1.amzn2022.src.rpm
Repository   : amazonlinux
Summary      : Amazon CloudWatch Agent
License      : MIT
Description  : This package provides daemon of Amazon CloudWatch Agent

```
