### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by pixie79** [amazonlinux/amazon-linux-2022#60]
Hi,

Is there a AL2022 docker base container image? It would be great to use as a replacement for the standard Amazon linux 2 image.

Thanks

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by skyzyx** [comment]
We custom-build certain packages that are not available in the upstream AL2 repos (and also for other distributions we support in-house). Having a Docker image available would allow us to add AL2022 to our automated build pipeline.

**Comment by stewartsmith** [comment]
I believe this is a duplicate of https://github.com/amazonlinux/amazon-linux-2022/issues/2 - we will have container images.
