### ISSUE TITLE
libreoffice doesnt start

### ISSUE THREAD

**Issue by PreetiMishra89** [amazonlinux/amazon-linux-2022#61]
$ libreoffice --version
LibreOffice 5.3.6.1 30(Build:1)

When ever i want to start the libreoffice it doesn't start!! 
How can i get the GUI up and running.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by stewartsmith** [comment]
We do not currently have LibreOffice in the AL2022 repositories. Are you downloading binaries from somewhere and trying to get them to run? You will need to install several X11 bits to get remote X11 to work in order to start LibreOffice in that kind of setup.
