### ISSUE TITLE
[Feature Request] - Smaller "minimal" ami boot drive

### ISSUE THREAD

**Issue by petercooperjr** [amazonlinux/amazon-linux-2022#63]
**Is your feature request related to a problem? Please describe.**
The current "minimal" Amazon Linux 2 AMI uses a boot drive of 2 GB. However, the minimal Amazon Linux 2022 AMI (or at least the one I tried, ami-02bdfdab82d25cec2 al2022-ami-minimal-2022.0.20211201.0-kernel-5.10-arm64) uses a 6GB boot drive. The snapshot backing the AMI is the smallest allowed for the boot drive when launching an instance. This means that if I were to switch to Amazon Linux 2022 when just spinning up a little server that doesn't really need drive space, I would need to pay for 6GB every month rather than just 2, tripling the EBS costs.

**Describe the solution you'd like**
When building the snapshot for the minimal image, use a 2GB drive rather than 6GB, like Amazon Linux 2 AMIs do. It looks like only 1.1GB is actually used on the drive, so this should still be plenty of space.

**Describe alternatives you've considered**
Well, I'm guessing I could copy the data to my own smaller snapshot and build my own AMI, but I at least find it convenient to just use the Amazon AMIs directly and just configure them with user-data.

**Additional context**
The non-minimal AMI uses an 8GB snapshot boot drive. I would have thought that one of the main advantages of the minimal version was the smaller drive, but if the minimal is still 6GB then it doesn't seem that much smaller.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by petercooperjr** [comment]
I can confirm that ami-0a3202000db619969 (al2022-ami-minimal-2022.0.20220504.1-kernel-5.15-arm64) worked with a 2gb boot drive. Thank you very much!
