### ISSUE TITLE
[Bug] - SSH to Amazon Linux 2022 arm64 instance times out

### ISSUE THREAD

**Issue by jeremiahsnapp** [amazonlinux/amazon-linux-2022#64]
**Describe the bug**

I created an EC2 instance using the Amazon Linux 2022 arm64 AMIs on an `a1.large` instance but I can't SSH into it. It just times out with the following output.

```
ssh: connect to host 172.19.136.149 port 22: Operation timed out
```

When I use the x86_64 AMI on an appropriate instance type I am able to SSH just fine.

I tried using the following standard Amazon Linux 2022 arm64 AMIs.

```
ami-0aabf70acbe6bdd20
ami-0920f6c3ccc54d46b
ami-0a3db10d0da51860e
```

I even tried using the following minimal Amazon Linux 2022 arm64 AMI.

```
ami-0d05b0f33ff6aa76e
```

Trying to SSH into any of them resulted in a timeout.

**To Reproduce**

Create an EC2 instance using the `ami-0a3db10d0da51860e` AMI and any arm64 instance type such as `a1.large`. Then try to SSH to it.

**Expected behavior**

I should be able to SSH to the instance.

**Comment by stewartsmith** [comment]
For ARM instances, we only support Graviton 2 and higher, which excludes a1 instance types. There is some docs on this, but perhaps there's a suggestion to where to make it clearer?

**Comment by jeremiahsnapp** [comment]
Thanks! Using graviton 2 instance types fixed my problem. I didn't stumble on anything about Graviton 2 requirements when I was trying to use Amazon Linux 2022. For example, I think it would be helpful if it was mentioned somewhere in these docs.

https://docs.aws.amazon.com/linux/al2022/ug/get-started.html

**Comment by Kemotaha** [comment]
We will take a look about what we can add to the getting started guide to help out.  Thanks for suggesting it!
