### ISSUE TITLE
[Missing Documentation] - How to install with EC2 SSM Console

### ISSUE THREAD

**Issue by driverpt** [amazonlinux/amazon-linux-2022#66]
UserData Script to install SSM Agent

**Comment by crabby345** [comment]
#!/bin/bash
dnf install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
systemctl enable --now amazon-ssm-agent

I think documenting this is unnecessary. The production build should have it baked in like al2, ideally available for update in repo (although al2 doesn't). It's also documented under installing SSM agent.

**Comment by driverpt** [comment]
> I think documenting this is unnecessary

I'm not even going to comment this.

> It's also documented under installing SSM agent

Yes, for AL2.

**Comment by jimilinuxguy** [comment]
Why was this removed from the base image? Its baked into the other official Amazon Linux AMIs. We are having to install it via userdata scripts and its clunky. WIll this be in the GA release?

**Comment by stewartsmith** [comment]
The `amazon-ssm-agent` package is in the `2022.0.20220728` release, and in the same AMIs that it was in in AL2.
