### ISSUE TITLE
[Feature Request] - aws cli v2 is preferable

### ISSUE THREAD

**Issue by bateleurX** [amazonlinux/amazon-linux-2022#71]
**Is your feature request related to a problem? Please describe.**
Amazon linux 2022 contains aws cli v1, which is installed via dnf.
But cli v1 is not recommended(*1) and some features which are provided to v2 might be not implement to v1 branch.
(*1): https://docs.aws.amazon.com/cli/v1/userguide/cli-chap-install.html
```
The AWS CLI version 1 is currently supported, but new features added to the AWS CLI version 2 may not be added to the AWS CLI version 1. To use those features, you must install the AWS CLI version 2.
```
**Describe the solution you'd like**
Upgrading preinstalled aws cli to v2.

**Describe alternatives you've considered**
Deleting aws cli v1 rpm package and downloading and installing v2 packages manually (or defining former process in custom AMI building system)

**Additional context**

**Comment by stewartsmith** [comment]
Our plan is to ship with AWS CLI v2 by default for AL2022.

**Comment by stewartsmith** [comment]
An update here as there's been a bunch going on.

We've been working with the AWS CLI team on https://github.com/aws/aws-cli/pull/6352 (now merged), and the various AWS SDK teams that work on the SDKs that the new CLI version depends on.

We're both still actively going through all the new dependencies of AWS CLI v2 over v1 for inclusion into upstream Fedora, and have been pulling them into a soon to be going out release of AL2022.

There's still some of these packages needing some reviews, and extra eyes are always welcome.

See also:
- https://bugzilla.redhat.com/show_bug.cgi?id=2049808 (the `awscli-2` package review for Fedora)
- [Bug 2049689](https://bugzilla.redhat.com/show_bug.cgi?id=2049689) - Review Request: `python-awscrt` - Python bindings for the AWS Common Runtime
- [Bug 2049644](https://bugzilla.redhat.com/show_bug.cgi?id=2049644) - Review Request: `aws-c-io` - This is a module for the AWS SDK for C.
- [Bug 2049656](https://bugzilla.redhat.com/show_bug.cgi?id=2049656) - Review Request: `aws-c-compression` - C99 implementation of huffman encoding/decoding
- [Bug 2049662](https://bugzilla.redhat.com/show_bug.cgi?id=2049662) - Review Request: `aws-c-http` - C99 implementation of the HTTP/1.1 and HTTP/2 specifications
- [Bug 2049716](https://bugzilla.redhat.com/show_bug.cgi?id=2049716) - Review Request: `aws-c-checksums` - Checksum package for AWS SDK for C
- [Bug 2049748](https://bugzilla.redhat.com/show_bug.cgi?id=2049748) - Review Request: `aws-c-event-stream` - C99 implementation of the vnd.amazon.eventstream content-type
- [Bug 2049781](https://bugzilla.redhat.com/show_bug.cgi?id=2049781) - Review Request: `aws-c-mqtt` - C99 implementation of the MQTT 3.1.1 specification
- [Bug 2049792](https://bugzilla.redhat.com/show_bug.cgi?id=2049792) - Review Request: `aws-c-s3` - C99 library implementation for communicating with the Amazon S3 service
- [Bug 2049382](https://bugzilla.redhat.com/show_bug.cgi?id=2049382) - Review Request: `aws-c-auth` - C99 library implementation of AWS client-side authentication: standard credentials providers and signing.
- [Bug 2049397](https://bugzilla.redhat.com/show_bug.cgi?id=2049397) - Review Request: `aws-c-sdkutils` - AWS SDK Utility library
- [Bug 2049400](https://bugzilla.redhat.com/show_bug.cgi?id=2049400) - Review Request: `aws-c-cal` - Aws Crypto Abstraction Layer: Cross-Platform, C99 wrapper for cryptography primitives.
- [Bug 2049379](https://bugzilla.redhat.com/show_bug.cgi?id=2049379) - Review Request: `aws-c-common` - Core c99 package for AWS SDK for C

**Comment by stewartsmith** [comment]
In our 2022.0.20220628 release, AWS CLI v2 is there.

We'll have AMIs and container images for this release shortly, but in the meantime you can update to it with: `dnf update --releasever=2022.0.20220628`

As you can see, `awscli` v2 is there:

```
bash-5.1# dnf info awscli-2
Last metadata expiration check: 0:13:59 ago on Fri Jul  1 15:37:14 2022.
Available Packages
Name         : awscli-2
Version      : 2.7.8
Release      : 1.amzn2022.0.1
Architecture : noarch
Size         : 7.3 M
Source       : awscli-2-2.7.8-1.amzn2022.0.1.src.rpm
Repository   : amazonlinux
Summary      : Universal Command Line Environment for AWS, Version 2
URL          : https://github.com/aws/aws-cli
License      : ASL 2.0 and MIT
Description  : 
             : This package provides version 2 of the unified command line
             : interface to Amazon Web Services.

bash-5.1# dnf install awscli
Last metadata expiration check: 0:14:04 ago on Fri Jul  1 15:37:14 2022.
Dependencies resolved.
==========================================================================================================================================================
 Package                                      Architecture               Version                                    Repository                       Size
==========================================================================================================================================================
Installing:
 awscli-2                                     noarch                     2.7.8-1.amzn2022.0.1                       amazonlinux                     7.3 M
Installing dependencies:
....
```
