### ISSUE TITLE
mariadb-server for Graviton

### ISSUE THREAD

**Issue by jiripik** [amazonlinux/amazon-linux-2022#72]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**

I run openssl + apache + php + mariadb on c5.large. I would like to be able to run the same on c7g.large. 

**Is this an update to existing package or new package request?**

While there is a mariadb-server package for Ubuntu running on Graviton, there is none for AWS Linux 2022 running on Graviton.

**Is this package available in Amazon Linux 2?**

Via a workaround, it's possible to download it for Intel CPUs.

**Number of users impacted**

A lot.

**Comment by stewartsmith** [comment]
MariaDB is available in the AL2022 repos for aarch64. While not in the initial preview, if you ensure you're running 2022.0.20211222 (as of writing the latest release) then you should see the packages in the repo. If you're running an older version, you can run `dnf update --releasever=2022.0.20211222` to upgrade.

```
$ arch
aarch64
$ sudo dnf install mariadb105-server
Last metadata expiration check: 0:01:26 ago on Mon 03 Jan 2022 07:12:33 PM UTC.
Dependencies resolved.
=========================================================================================================================
 Package                                Architecture      Version                            Repository             Size
=========================================================================================================================
Installing:
 mariadb105-server                      aarch64           3:10.5.12-1.amzn2022.0.1           amazonlinux           9.7 M
```
