### ISSUE TITLE
[Feature Request] - Periodic Updates of OpenSSL, httpd, php and MariaDb

### ISSUE THREAD

**Issue by jiripik** [amazonlinux/amazon-linux-2022#73]
**Is your feature request related to a problem? Please describe.**
The official OpenSSL version in the Amazon Linuxes have always been like 2+ year behind, meaning the versions were with known security risks.

A slightly better situation for httpd, php, and mariadb.

**Describe the solution you'd like**
Amazon Linux 2022 to have the version of OpenSSL, php, apache httpd and mariadb a version behind the latest version.

**Describe alternatives you've considered**
Manual building the packages but it's too difficult.

**Additional context**

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by stewartsmith** [comment]
We are shipping OpenSSL 3 in AL2022. We are keeping up to date with Apache httpd releases, and MariaDB 10.5 and PHP 8.1 are currently in Amazon Linux 2022.

We will make newer versions available over time and as they are released,
