### ISSUE TITLE
[Package Request] - Add Support for Realmd 

### ISSUE THREAD

**Issue by johnowens00** [amazonlinux/amazon-linux-2022#74]
Realmd allows us to join AL2022 images to Active Directory domains.   This feature exists in Amazon Linux 2 but not in AL2022.  The package is available from the upstream Fedora repos.   

New Package Request

Yes.

Please include the ability to install realmd and its dependencies in AL2022 to allow for enterprise authentication into Linux instances build with this OS. 

This may impact a LOT of companies that use AD for SSO in their Enterprise.

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by johnowens00** [comment]
Any update on this?  You originally replied in February.

**Comment by b3rgman** [comment]
Is there an update on this?  I also require this package.

**Comment by johnowens00** [comment]
> Is there an update on this? I also require this package.

Check the latest build.  They added it.  Along w/ adcli.

**Comment by b3rgman** [comment]
Couldn't tell as this issue is still `open`.  Paging through all the package requests.  I need several of them.  Thanks @johnowens00

**Comment by stewartsmith** [comment]
Yep, it appears we have `realmd` and just missed closing this issue, doing so now.
