### ISSUE TITLE
[Package Request] - docker-ce/docker-ce-cli/containerd.io

### ISSUE THREAD

**Issue by amrragab8080** [amazonlinux/amazon-linux-2022#78]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
docker-ce/docker-ce-cli/containerd.io

**Is this an update to existing package or new package request?**
new

**Is this package available in Amazon Linux 2?**
its available through the amazon-linux-extras

**Number of users impacted**

**Comment by amrragab8080** [comment]
If the intent is to use the fedora repo for docker that fails too.
```
dnf config-manager     --add-repo     https://download.docker.com/linux/fedora/docker-ce.repo
```
mainly because the fedora resolves the version based on 2022 which doesnt exist in the repo
```
[root@ip-172-31-47-15 ~]# dnf install docker-ce docker-ce-cli containerd.io
Docker CE Stable - x86_64                                          3.6 kB/s | 397  B     00:00    
Errors during downloading metadata for repository 'docker-ce-stable':
  - Status code: 404 for https://download.docker.com/linux/fedora/**2022.0.20211222**/x86_64/stable/repodata/repomd.xml (IP: 13.32.151.28)
```

**Comment by jimilinuxguy** [comment]
> [root@ip-172-31-47-15 ~]# dnf install docker-ce docker-ce-cli containerd.io
Docker CE Stable - x86_64                                          3.6 kB/s | 397  B     00:00    
Errors during downloading metadata for repository 'docker-ce-stable':
  - Status code: 404 for https://download.docker.com/linux/fedora/**2022.0.20211222**/x86_64/stable/repodata/repomd.xml (IP: 13.32.151.28)

@amrragab8080 I temporarily am working around this same issue by manually editing the /etc/yum.repos.d/docker-ce.repo replacing $releasever with 34. Its not an ideal solution but it works for now. I am hoping that AWS takes these requests into consideration with more weight.

**Comment by amrragab8080** [comment]
Yes I did the same, this more of a tracking ticket to get the collection of dependencies and rpms into the next update hopefully.

**Comment by njacklin1988** [comment]
Docker is shipped now on AL2022
