### ISSUE TITLE
[Feature Request] - Upgrade Systemd with newer version for Docker Desktop >=4.3.0

### ISSUE THREAD

**Issue by triwats** [amazonlinux/amazon-linux-2022#85]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
[Since Docker Desktop 4.3.0 for MacOS, there is a minimum requirement for systemd 2.47.0](https://docs.docker.com/desktop/mac/release-notes/#bug-fixes-and-minor-changes-1) for it to run properly within a Docker Container. Without this, we never get DBus to start up as we were able to in other versions of Docker Desktop. That being said, the version of 

We test our [ansible](https://www.ansible.com/)  changes locally when creating immutable infrastructure, and then pass that off to our build process in CI/CD. However, due to us being on MacOS, we are now unable to connect to DBus if we install systemctl and do the expected workarounds to get systemctl to work via Docker.

Without these crucial steps to put Systemctl onto a container, the `cgroupsns` option is seemingly unsupported in the current version (`systemd-219`) and thus never starts properly.

To start a container with systemd via Docker desktop, we can do this:

```docker run --tmpfs /run --privileged --cgroupns=host --volume /sys/fs/cgroup:/sys/fs/cgroup:rw -it amazonlinux:latest /usr/lib/systemd/systemd```

Then we can connect into that container specifically to test if this works. It returns the following:

```
$ systemctl
Error: "Failed to connect to bus: No such file or directory"
```

As a caveat, the standalone Docker Engine Engine seems to work, this only impacts local testing or usage of Docker Desktop.

**Is this an update to existing package or new package request?**
An update to SystemD and relevant packages

**Is this package available in Amazon Linux 2?**
Yes, but the version is outdated. 

```
bash-4.2# rpm -qa | grep -i systemd
systemd-libs-219-78.amzn2.0.15.aarch64
systemd-219-78.amzn2.0.15.aarch64
```

Note the documentation from Docker above states that users should update to Centos 8 to mitigate these issues. I believe that Amazon Linux 2022 should be in line with that.

**Number of users impacted**
Unknown

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by stewartsmith** [comment]
`2022.0.20220315` is currently shipping with `systemd` version 248.

You mention `amazonlinux:latest` as a container, but this is Amazon Linux 2 as AL2022 is currently in tech preview and not the latest GA release (at least yet).

We're not looking at making major changes to the `systemd` version in AL2, but are always looking at possible bug fixes that can be non-disruptive to production workloads.
