### ISSUE TITLE
[Package Request] - mc

### ISSUE THREAD

**Issue by ecofor** [amazonlinux/amazon-linux-2022#90]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
mc

**Is this an update to existing package or new package request?**

**Is this package available in Amazon Linux 2?**
Is available in AMZN2

**Number of users impacted**
Only me, 40+ years using Norton Commander/Midnight Commander ... please make this little effort!! Thank you!!!

**Comment by incitem** [comment]
Duplicate, see https://github.com/amazonlinux/amazon-linux-2022/issues/48

**Comment by ecofor** [comment]
> Duplicate, see #48

You're right!!!

**Comment by liesenml** [comment]
closing as this is a duplicate
