### ISSUE TITLE
[Package Request] - rpmdevtools & rpmlint

### ISSUE THREAD

**Issue by q2ven** [amazonlinux/amazon-linux-2022#91]
**What package is missing from Amazon Linux 2022? Please describe and include package name.**
rpmdevtools & rpmlint

**Is this an update to existing package or new package request?**
Existing packages in Amazon Linux 2.

**Is this package available in Amazon Linux 2?**

They are installable from amzn2-core repository.

```
$ sudo yum search rpmdevtools rpmlint
...
rpmdevtools.noarch : RPM Development Tools
...
rpmlint.noarch : Tool for checking common errors in RPM packages
```

**Number of users impacted**
N/A

**Comment by elsaco** [comment]
@q2ven `rpmdevtools` and `rpmlint` are available already:

```
[~]$ dnf search rpmdevtools
Last metadata expiration check: 0:00:41 ago on Mon 14 Feb 2022 11:57:32 PM UTC.
========================================== Name Exactly Matched: rpmdevtools ===========================================
rpmdevtools.noarch : RPM Development Tools
[~]$ dnf search rpmlint
Last metadata expiration check: 0:00:56 ago on Mon 14 Feb 2022 11:57:32 PM UTC.
============================================ Name Exactly Matched: rpmlint =============================================
rpmlint.noarch : Tool for checking common errors in RPM packages

```

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by njacklin1988** [comment]
Both these are available on AL2022:
