### ISSUE TITLE
Kernel 5.11 or inclusion of unprivileged overlayfs fix

### ISSUE THREAD

**Issue by dg424** [amazonlinux/amazon-linux-2022#98]
Hi,

Please see here - https://github.com/torvalds/linux/commit/459c7c565ac36ba09ffbf24231147f408fde4203
We run rootless containers on AWS, but it is not possible to use overlayfs with Amazon Linux 2 because it's still on kernel 5.10. Is it possible to add this to the 2022 roadmap ?

Thanks

**Comment by liesenml** [comment]
Hello, thank you for submitting your request! We review all requests on a weekly basis and will reply to this ticket by with our evaluation.

**Comment by stewartsmith** [comment]
https://github.com/amazonlinux/amazon-linux-2022/issues/4 was about including kernel 5.15 in Amazon Linux 2022. We have the kernels in the repos and AMIs are rolling out, so this is either already done, or really close to being done done done.

**Comment by dg424** [comment]
Nice! Is there an AMI released right now that we can use ?
